const misproductos = [
  {
    id: 1,
    nombre: "Remera básica blanca",
    descripcion: "Remera 100% algodón, corte clásico",
    precio: 5000,
    categoria: "remeras",
  },
  {
    id: 2,
    nombre: "Jean azul clásico",
    descripcion: "Jean de corte recto, denim resistente",
    precio: 12000,
    categoria: "pantalones",
  },
  {
    id: 3,
    nombre: "Campera liviana",
    descripcion: "Campera impermeable ideal para entretiempo",
    precio: 18000,
    categoria: "camperas",
  },
  {
    id: 4,
    nombre: "Remera negra estampada",
    descripcion: "Remera con estampa frontal y tela suave",
    precio: 5500,
    categoria: "remeras",
  },
  {
    id: 5,
    nombre: "Pantalón cargo verde",
    descripcion: "Pantalón con bolsillos laterales y tela resistente",
    precio: 13500,
    categoria: "pantalones",
  },
  {
    id: 6,
    nombre: "Campera de abrigo con capucha",
    descripcion: "Ideal para invierno, relleno térmico",
    precio: 25000,
    categoria: "camperas",
  },
  {
    id: 7,
    nombre: "Bermuda de jean",
    descripcion: "Bermuda clásica para el verano",
    precio: 8000,
    categoria: "bermudas",
  },
  {
    id: 8,
    nombre: "Camisa blanca manga larga",
    descripcion: "Camisa formal 100% algodón",
    precio: 11000,
    categoria: "camisas",
  },
  {
    id: 9,
    nombre: "Zapatillas urbanas",
    descripcion: "Zapatillas cómodas para uso diario",
    precio: 20000,
    categoria: "calzado",
  },
  {
    id: 10,
    nombre: "Botines de cuero",
    descripcion: "Botines clásicos de cuero marrón",
    precio: 28000,
    categoria: "calzado",
  },
  {
    id: 11,
    nombre: "Buzo con capucha gris",
    descripcion: "Buzo de algodón con capucha y bolsillo frontal",
    precio: 15000,
    categoria: "buzos",
  },
  {
    id: 12,
    nombre: "Sweater cuello redondo",
    descripcion: "Sweater de lana suave, ideal para otoño",
    precio: 16000,
    categoria: "sweaters",
  },
  {
    id: 13,
    nombre: "Remera rayada",
    descripcion: "Remera liviana con rayas horizontales",
    precio: 5300,
    categoria: "remeras",
  },
  {
    id: 14,
    nombre: "Pantalón jogging",
    descripcion: "Jogging deportivo con puños y cintura ajustable",
    precio: 9500,
    categoria: "pantalones",
  },
  {
    id: 15,
    nombre: "Camisa de jean",
    descripcion: "Camisa casual de denim",
    precio: 12500,
    categoria: "camisas",
  },
  {
    id: 16,
    nombre: "Bermuda cargo",
    descripcion: "Bermuda con múltiples bolsillos",
    precio: 8500,
    categoria: "bermudas",
  },
  {
    id: 17,
    nombre: "Buzo estampado juvenil",
    descripcion: "Buzo con diseño moderno y juvenil",
    precio: 14800,
    categoria: "buzos",
  },
  {
    id: 18,
    nombre: "Sweater escote en V",
    descripcion: "Ideal para oficina o casual",
    precio: 15800,
    categoria: "sweaters",
  },
];

export default misproductos;
